drivers: media: Import Xiaomi platform changes for ugglite
Add 'drivers/staging/prima/' from commit 'b5ec3426f5712ea3cf2552557e380408a9eba5a7'

git-subtree-dir: drivers/staging/prima
git-subtree-mainline: 58baeded4a473f6bbf465e97d4c22fd29f14009d
git-subtree-split: b5ec3426f5712ea3cf2552557e380408a9eba5a7

Signed-off-by: Albert I <kras@raphielgang.org>

staging: prima: Cleanup unused files

Change-Id: I23d65bc818a13496ffcebefa8e27a167521857f2
Signed-off-by: Albert I <kras@raphielgang.org>

staging: prima: Add Kconfig entry for TDLS

Change-Id: I670c8d7eb24de9f431d8dd89a8694fa216f4f9ff
Signed-off-by: Albert I <kras@raphielgang.org>

staging: prima: Fix non-debug build and switch to it

Enable the forward declaration of debug functions in non-debug
builds and disable a piece of code used only to print some info.
-Wno-unused-variable is now required because of all the variables
used in debug functions that aren't left out in non-debug builds.

Change-Id: I7069f8859e4965ee82ce65c29c35349c887fd673
Signed-off-by: Albert I <kras@raphielgang.org>

prima: Make -Wno-maybe-uninitialized to use cc-disable-warning

warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]

Change-Id: I488ba044a23da5c06730ebe31b50ccd28ea0c8ae
Signed-off-by: Albert I <kras@raphielgang.org>

drivers: staging: prima: fix clang warning non-literal-null-conversion

/home/adek/kernel/msm8953/drivers/staging/prima/CORE/MAC/src/pe/lim/limLogDump.c:308:72: warning:
      expression which evaluates to zero treated as a null pointer constant of type
      'void *' [-Wnon-literal-null-conversion]
  ...mesg = { (tANI_U16) SIR_LIM_BEACON_GEN_IND, (tANI_U16) 0, (tANI_U32) 0 };
                                                               ^~~~~~~~~~~~
1 warning generated.

Change-Id: I3ab4b7114aeab32593abea75b7b6fd819b3cac70
Signed-off-by: Albert I <kras@raphielgang.org>

prima: Fix for loop has empty body

Silence these warnings:

../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4096:43: error: for loop has empty body [-Werror,-Wempty-body]
   for (ptr = str; i_isspace(*ptr); ptr++);
                                          ^
../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4096:43: note: put the semicolon on a separate line to silence this warning
../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4105:48: error: for loop has empty body [-Werror,-Wempty-body]
   for (; ptr != str && i_isspace(*ptr); ptr--);
                                               ^
../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4105:48: note: put the semicolon on a separate line to silence this warning

Signed-off-by: khusika <khusikadhamar@gmail.com>
[kras: Little fix to commit message]
Signed-off-by: Albert I <kras@raphielgang.org>

prima: Remove redefinition of pEncryptMsgRSPCb

Clang spams the build with the following warnings (trimmed):

  In file included from /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/MAC/src/pe/lim/limStaHashApi.c:39:
  In file included from /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/MAC/src/pe/lim/limStaHashApi.h:45:
  In file included from /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/MAC/inc/aniGlobal.h:73:
  In file included from /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/SME/inc/csrInternal.h:55:
  In file included from /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/SME/inc/csrNeighborRoam.h:42:
  /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/SME/inc/sme_Api.h:3859:15: warning: redefinition of typedef 'pEncryptMsgRSPCb' is a C11 feature [-Wtypedef-redefinition]
  typedef void(*pEncryptMsgRSPCb)(void *pUserData, void *infoParam);
                ^
  /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/SME/inc/smeInternal.h:138:15: note: previous definition is here
  typedef void(*pEncryptMsgRSPCb)(void *pUserData, void *infoParam);
                ^

Since sme_Api.h includes smeInternal.h, we can safely remove the
definition from sme_Api.h without breaking the entire build.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Disable enum-conversion warning

This driver and qcacld-2.0 suck due to how mixed up logics between
enums are used. Not worth fixing.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Remove pointless null checks

Code quality of prima sucks, hence I'm fixing it the lazy way.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Don't get out of array index data on wlan_ftm_priv_get_rx_rssi()

/mnt/ssd/kernels/mido/drivers/staging/prima/CORE/HDD/src/wlan_hdd_ftm.c:4741:19: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
                  pMsgBody->GetRxRssi.rssi.rx[1]);
                  ^                           ~
/mnt/ssd/kernels/mido/drivers/staging/prima/riva/inc/wlan_phy.h:299:5: note: array 'rx' declared here
    tANI_U8 rx[PHY_MAX_RX_CHAINS];
    ^

rx has only one member (0), so remove the second, out of array one.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Remove redundant semicolon in bslWriteFinish()

So it actually does the "sanity check".

/mnt/ssd/kernels/mido/drivers/staging/prima/CORE/HDD/src/bap_hdd_main.c:4287:60: warning: if statement has empty body [-Wempty-body]
    if ( pctx != (BslClientCtxType *)hci_get_drvdata(hdev));
                                                           ^

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Remove extraneous parentheses

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Avoid VOS_GET_HAL_CB macro re-definition

undef previous macro before setting a new one to make both core
and BT-AMP drivers happy.

 In file included from /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/HDD/src/wlan_hdd_main.c:123:
 /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/SAP/src/sapInternal.h:102:9: warning: 'VOS_GET_HAL_CB' macro redefined [-Wmacro-redefined]
 #define VOS_GET_HAL_CB(ctx) vos_get_context( VOS_MODULE_ID_PE, ctx)
         ^
 /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/BAP/src/bapInternal.h:117:9: note: previous definition is here
 #define VOS_GET_HAL_CB(ctx) vos_get_context( VOS_MODULE_ID_SME, ctx)
         ^

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Remove redefinition of tpAniSirGlobal

Already defined in sirApi.h included by sme_Api.h.

/mnt/ssd/kernels/mido/drivers/staging/prima/CORE/BAP/src/btampFsm.c:101:31: warning: redefinition of typedef 'tpAniSirGlobal' is a C11 feature [-Wtypedef-redefinition]
typedef struct sAniSirGlobal *tpAniSirGlobal;
                              ^
/mnt/ssd/kernels/mido/drivers/staging/prima/CORE/MAC/inc/sirApi.h:47:31: note: previous definition is here
typedef struct sAniSirGlobal *tpAniSirGlobal;
                              ^

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Increase frame-larger-than limit for Clang

Matches 64-bit configuration.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Fix a qcacld-3.0 commit port derp

Changes done by the following commit:
  https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/prima/commit/?h=LA.UM.7.6.r1-06700-89xx.0&id=626f8655c62c0b61d0bcba19b6230046da76e891

Causes a compilation error, which is later traced from (probably) a
mismerge from CAF side. This commit does the following changes:
 * Correct the mismerge by placing the redundant break at its proper place.
 * Guard eLIM_AUTH_SAE_TIMER under WLAN_FEATURE_LFR_MBB.

Error log:
  /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/MAC/src/pe/lim/limTimerUtils.c:1956:10: error: use of undeclared identifier 'eLIM_AUTH_SAE_TIMER'
      case eLIM_AUTH_SAE_TIMER:
           ^
  1 error generated.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Fix BT-AMP compilation on Linux 3.13+

Fixing up to msm-3.18.

- hci_recv_frame() definition is changed since commit e1a26170692d
- hdev->ioctl has been removed since commit 324d36ed26a2
- Also remove several redefinitions that break the build.

Signed-off-by: Albert I <kras@raphielgang.org>

Merge tag 'LA.UM.8.6.r1-04000-89xx.0' into LA.UM.8.6.r1

* caf/msm-3.18/kernel.lnx.3.18.r41-rel:
  msm: vidc: avoid OOB write while accessing memory
  msm: camera : Lock Implementation for avoid race condition
  msm: camera: Fix for OOB security CR
  Clarify (and fix) MAX_LFS_FILESIZE macros
  proc: update perms of node "reclaim"

* caf/prima/wlan-driver.lnx.1.0.r33-rel:
  wlan: Avoid queuing multiple WM status change cmd for same peer
  wlan: Add max index check for dscp_to_up_map array
  wlan: Avoid queuing multiple WM status change cmd for same peer
  wlan: Remove FW memory dump feature
  prima: Verify pmk len in construct RSn IE API
  wlan: Remove CSR dot11f IE RSN max len
  wlan: Initialize the pmkid cache variable
  wlan: Add max index check for dscp_to_up_map array
  wlan: fix buffer overflow in psessionEntry->pSchBeaconFrameBegin
  wlan : disable clang warning
  wlan: Disable per packet tx rx and connect event logging
  wlan: Validate bss with the correct bss address
  wlan: Update spoof mac address in TL for roam scan

Signed-off-by: Albert I <kras@raphielgang.org>

Revert "wlan : disable clang warning"

This reverts commit 5590f00b4cdab129ef6df1d232cef8563d1e0658.

Not only the way CAF disabling these warnings are literal mess (due to
missing guard), most of these warnings can be fixed; which I already
did in 'LA.UM.8.6.r1/compiler-fixes' branch.

For CAF: Don't forget that msm-3.18 still uses GCC at all costs.

Signed-off-by: Albert I <kras@raphielgang.org>

Merge tag 'LA.UM.8.6.r1-04200-89xx.0' into LA.UM.8.6.r1

* caf/msm-3.18/kernel.lnx.3.18.r41-rel:
  mremap: properly flush TLB before releasing the page
  msm: camera: jpegdma: Fix uninitialized variable

* caf/prima/wlan-driver.lnx.1.0.r33-rel:
  wlan: Fix integer overflow in rrm_fill_beacon_ies()
  wlan: Validate assoc response IE len before copy
  qcacld-2.0: Check for minimum frameLen for action frames
  wlan: Validate assoc response IE len before copy
  wlan: Remove off-by-one write condition in sch_beacon_process

Signed-off-by: Albert I <kras@raphielgang.org>

wlan: Remove WLAN_FEATURE_HOLD_RX_WAKELOCK feature

- WLAN_FEATURE_HOLD_RX_WAKELOCK feature acquires 50 ms wake lock for
  every rx data packet.
- Remove this feature such that we can avoid wake lock for every RX
  data packet.

Change-Id: I90c8441694aac5a2df029def5f8b7f5d62eee484
CRs-Fixed: 929621
Signed-off-by: Albert I <kras@raphielgang.org>

Revert "staging: prima: Add Kconfig entry for TDLS"

This reverts commit a52ab79a4f90ed2ccf4d4a4fc560d7ea4dbc2716.

Just discard Kconfig-based configuration entirely.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Drop Kconfig-based configuration entirely

Kconfig entries are never in sync with out-of-tree module configuration, hence
dropping this altogether and make use such configuration for all. Features can
be configured by directly modifying flags on drivers/staging/prima/Kbuild that
start with 'CONFIG_'.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Kbuild: Add missing Kbuild entry for a3042b630a94

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Update indentations to fix compiler warnings

GCC 6+ and Clang 11+ warn whenever indentations are considered misleading
especially when they think that codes are misinterpreted as if being guarded
by conditions above them.

While we're at it, fix some of horrible if usage as seen with overlap
statements.

Signed-off-by: Albert I <kras@raphielgang.org>

prima: Remove extraneous parentheses (part 2)

Completes commit 28b3c5ea9cad, with test done across all features of the driver.

Signed-off-by: Albert I <kras@raphielgang.org>